#!/usr/bin/env python
import click
import subprocess
import os

@click.group()
def mynode():
    pass

@mynode.command()
def init():
    print(f"init: {os.getcwd()}")
    input()

    subprocess.run("git clone https://github.com/gnulnx/mynode_backend backend", shell=True, check=True)
    subprocess.run("git clone https://github.com/gnulnx/mynode_frontend frontend", shell=True, check=True)

if __name__ == '__main__':
    mynode()
